### ISSUE TITLE
Node.js Foundation Website Redesign Initiative Meeting 2018-02-15

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#10]
From the past meeting's minutes, and discussion in #4, there seemed to be consensus that meetings would be every 2 weeks. In case that plan is ongoing, I'm opening this issue to get started. 

The agenda from the last meeting is preserved, with the addition of #4 because of some developments regarding content and structure. This can be modified as needed, I'm sure.

Meeting time has also been kept the same, as the last meeting's attendees were spread across a wide range of timezones.

**Time**
----
**UTC Thu 15-Feb-2018 15:00 (03:00 PM)**

Or in your local time:

https://www.timeanddate.com/worldclock/fixedtime.html?msg=Website+Redesign+Meeting+2018-02-15&iso=20180215T15&p1=%3A&ah=1

**Links**
----
* **Minutes Google Doc:** https://docs.google.com/document/d/1h3-YLjzeEZYKQQxscZUB44-jGmqFg4mwa0VO4VZb38Q/edit?usp=sharing
* **Previous Minutes Google Doc:** https://docs.google.com/document/d/1upCQqRI6BxClP6or1mvaQSVSXakzEEzWVStsnboqbVo/edit

**Agenda**
(As we're still in early stage discussion, like last time, these items can be reordered by suggested importance)

* Content structure #4 
* Getting started with Node #9 
* Should We Attempt an Update of Official Node.js Messaging https://github.com/nodejs/community-committee/issues/242
* Components library #5 

**Invited Members**
----
- @oe - Olivia Hugger
- @fhemberger - Frederic Hemberger
- @bnb - Tierney Cyren
- @timothyis - Timothy
- @jestho - Jesper Thøgersen
- @JonahMoses - Jonah Moses
- @amiller-gh - Adam Miller
- @skllcrn - Christopher Skillicorn
- @pierreneter - Pierre Neter
- @emilypmendez - Emily Mendez
- @darcyclarke - Darcy Clarke
- @maddhruv - Dhruv Jain
- @obensource - Ben Michel
- @Fishrock123 - Jeremiah Senkpiel
- @chowdhurian - Manil
- @franciscop - Francisco Presencia

**Joining the meeting**
--
Zoom Meeting; a link will be posted here shortly before the meeting starts.

If you're interested in joining the meeting, just ask in the issue and we will invite you!

**Public participation**
--
We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ/live when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

**Comment by keywordnew** [comment]
cc @oe ^_^

**Comment by ghost** [comment]
Thanks @chowdhurian!

**Comment by jestho** [comment]
Darn... I don't think I will be able to join this meeting either, unfortunately...

Regarding the components library, I definitely think this is a good way to go, but first we might want to decide what (if any) framework/library we want to use, and then choose the right tool for building the library. As I mentioned in #5, [Storybook](https://github.com/storybooks/storybook) is pretty great if we choose to go for React, Vue or Angular.

Also, before starting to build these components, we should have some wireframes in place, which would require us to nail down which design tools to use for best collaboration. As far as I know, [Sketch](https://www.sketchapp.com/) is the industry standard at the moment, but Mac only. Maybe we should look for an alternative like [Gravit](https://designer.io/) or [Figma](https://www.figma.com/).

**Comment by ghost** [comment]
@nodejs/website-redesign if anyone has a topic they'd like to see discussed in the meeting, please create an issue and add the `wr-agenda` label to it!

**Comment by fhemberger** [comment]
@jestho Again, we're not talking about implementation yet. We're still far from that point. So please let's discuss information architecture, design, content, localization, etc. first.

**Comment by oe** [comment]
I'd love if someone else could take care of moderating this week's meeting since I'm confined to a space where I can't talk much 😞  @bnb @amiller-gh perhaps?

**Comment by ghost** [comment]
@bnb is this on your schedule? if so, could you set up a zoom meeting?

**Comment by bnb** [comment]
@oe Yep, one sec. Didn't realize what time it was at 😬

**Comment by bnb** [comment]
@oe @nodejs/website-redesign join link: https://zoom.us/j/379471463

**Comment by JonahMoses** [comment]
Just as an FYI, This time (ends up being 7am-8am for me in PST) is dedicated to getting my kids up and ready for school so I will most likely never be able to make it if we keep it at this time. I don't want to have this meeting change just on my behalf if it works for everyone else but figured I'd chime in.

**Comment by emilypmendez** [comment]
I happened to only catch the very end of this meeting due to a previously scheduled meeting for this same time, as a consequence - I'll be referring to the notes on GDocs for keeping up to date on the progress of this project. Hoping to contribute on wireframes, noted for the record.
