### ISSUE TITLE
[Discussion] - Tech Stack Consideration

### ISSUE THREAD

**Issue by mbj36** [nodejs/website-redesign#107]
I want to open up the discussion related to selection of tech stack for redesign of NodeJS website

### **Challenges** 

- Pull out docs from NodeJS core repo
- Code Structure - which makes any other contributors to easily navigate through code and find contributing easily
- What are the content that we want to put up on website ?

### **Components Frameworks**

Are we going to use any open source UI framework i.e - Vue, React etc ?

### **Build Tools**

What are the build tools we can consider using ?

### **Static Site Generator**

[Gatsby](https://github.com/gatsbyjs/gatsby) -  Gatsby has been gaining huge popularity these days, Big companies are already using this as static site generator

Please feel free to edit/comment this issue as feel right. CC - @amiller-gh @chowdhurian

**Comment by fhemberger** [comment]
Just stumbled on [Docusaurus](https://docusaurus.io/en/) by Facebook, which might fit nicely as well:

**Docusaurus - Easy to Maintain Open Source Documentation Websites:**

- Uses Markdown
- Built on React
- Translations via Crowdin
- Document versioning
- Search via Agolia
- Generates static files

Used by React, Jest, Babel, Gulp, Prettier, Node SerialPort, …

**Comment by codeekage** [comment]
@fhemberger this is 100% solid! 😍😍 Just read the documentation and setting up is super easy and cool. Will def love to work with this.

**Comment by mbj36** [comment]
Not sure if we can pull data from other sources using Docusaurus. Because we might be pulling docs from nodejs core repo instead of having docs in website repo.

**Comment by fhemberger** [comment]
@mbj36 They are working on it: https://github.com/facebook/Docusaurus/issues/827

**Comment by amiller-gh** [comment]
Going to close this since we're actively working in Gatsby on `nodejs.dev` over in https://github.com/nodejs/nodejs.dev 🙏
