### ISSUE TITLE
Possible conflict with Individual Membership Subgroup meeting 

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#108]
The [Individual Membership Subgroup](https://github.com/nodejs/community-committee/labels/individual-membership) meeting is possibly moving to Thursdays at 1600 UTC because of a conflict with the [Bootstrap Committee](https://github.com/nodejs/bootstrap/issues) meetings which was in that slot because of its Board attendees who were already meeting at the time.

Fun, right? 👀

It's a good time to check to see if there is a more optimal meeting time for us now that it's been almost a year since we chose the time and the composition of our contributors has changed.

Since we have members from US, EU, and Asian timezones, we should aim for 1500 through 1700 UTC so that everyone can attend.

Here's a [doodle](https://doodle.com/poll/xtdfeqwzsqyw9zgc) with some options. Please choose the ones that work for you and comment below!

Please sign the poll with your github handle :)

Any changes we make will take effect after the next meeting ⚡️

**Comment by keywordnew** [comment]
@amiller-gh adding another option, of an hour up from the current time Thursday.

**Comment by keywordnew** [comment]
^^ pinging @nodejs/website-redesign 💛 what time works better for you?

**Comment by sagirk** [comment]
Would prefer the 1500 UTC (= 2030 IST) slot and Friday is the start of the weekend 😉, hence voted Monday.

**Comment by amiller-gh** [comment]
👍 sorry for the delay, voted

**Comment by keywordnew** [comment]
The Individual Membership Subgroup will not be moving its meetings. They're on hold until a new champion is found.

Thanks for voting! 🙏🏽
