### ISSUE TITLE
Migrate deprecated `new Buffer()` constructors to new APIs

### ISSUE THREAD

**Issue by sagirk** [nodejs/website-redesign#115]
In [`documentation/0051-node-buffers/index.md`](https://github.com/nodejs/website-redesign/blob/master/documentation/0051-node-buffers/index.md), `Buffer` constructors have been used multiple times.

`Buffer` constructors have been [deprecated](https://nodejs.org/api/buffer.html#buffer_new_buffer_size) since v6.0.0. 

>The `Buffer` constructor function allocates the returned `Buffer` differently based on what arguments are provided.
>
>Because the behaviour of `new Buffer()` is different depending on the type of the first argument, security and reliability issues can be inadvertently introduced into applications when argument validation or `Buffer` initialization is not performed.
>
>To make the creation of `Buffer` instances more reliable and less error-prone, the various forms of the `new Buffer()` constructor have been deprecated and replaced by separate `Buffer.from()`, `Buffer.alloc()`, and `Buffer.allocUnsafe()` methods.
>
> — [Node.js Documentation](https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe)

It is suggested to use [`Buffer.from(array)`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array), [`Buffer.from(arrayBuffer[, byteOffset[, length]])`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_arraybuffer_byteoffset_length), [`Buffer.from(buffer)`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_buffer), [`Buffer.alloc()`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding) and [`Buffer.from(string[, encoding])`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding) instead.

**Comment by lidoravitan** [comment]
@sagirk can I help with that? Do you think we should also add an explanation about the deprecated?

**Comment by sagirk** [comment]
@lidoravitan Sorry for the late reply. Yes, please! 👍 

1. I would have told you to raise an early PR after claiming the issue, but I see that you've done that already! You are awesome! ❤️

2. Adding an explanation about why an obsolete feature was deprecated would only be extra noise, IMO. A link to the official documentation should be enough (it is well covered in the docs).

**Comment by lidoravitan** [comment]
I'm excited to take part in this initiative and project, hoping to be an effective contributor. 💚

**Comment by sagirk** [comment]
Closed in https://github.com/nodejs/website-redesign/pull/116 and https://github.com/nodejs/website-redesign/pull/132.
