### ISSUE TITLE
Improve new Buffer() constructors documentation following the previous issue

### ISSUE THREAD

**Issue by lidoravitan** [nodejs/website-redesign#124]
**Context:** Improve new Buffer() constructors documentation following the previous issue #115, This issue is also part of action items from [20-12-2018](https://github.com/nodejs/website-redesign/issues/123) meeting.

@sagirk opened issue #115 about new Buffer() deprecated, which resolved by #116. However, @sagirk left some few comments.
  
**A. L32 - L35 can be gotten rid of. Reasons:**
1. Seeing these intricate details can look intimidating to a beginner.
Advanced users can always look up this info up in the API docs.
2. Seeing these intricate details can look intimidating to a beginner.
Advanced users can always look up this info up in the API docs.

**B. L33 - L35 You can optionally pass the encoding in the second parameter (defaults to UTF-8).**
1. This line can be retained. It can be useful to know, especially given that now we'll have an example for only this one form of using Buffer.from().

**C. L37 - You can also initialize a buffer with a size. This creates a 1KB buffer**
1. should be the old one - You can also just initialize the buffer passing the size. This creates a 1KB buffer.

**D. L41 - L42 - Can be gotten rid of Buffer.allocUnsafe()**
1. The reason is that we probably don't want to be teaching Buffer.allocUnsafe() to beginners in introductory material.
Because this is intended to be a getting started guide, it's okay (I hope!) to omit information that advanced users can look up in the API docs.

For more detaiils about request changes, #116.

**Comment by sagirk** [comment]
Closed in https://github.com/nodejs/website-redesign/pull/132
