### ISSUE TITLE
Knowledge base articles need to be reviewed ahead of pulling them in

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#126]
This [issue](https://github.com/nodejs/nodejs.org/issues/1977) was raised in the nodejs.org repo about content that was submitted by Nodejitsu to the Node.js project (not Website Redesign specifically). 

We have a [RFC process for bringing in new content](https://github.com/nodejs/website-redesign/tree/master/documentation#documentation-rfcs-request-for-comments). The content has yet to be reviewed but I think it can be funnelled into our existing RFC process.

Interested reviewers would need to visit [nodejs.org/en/knowledge](nodejs.org/en/knowledge):
- [ ] Pick an item by following the links to github and getting the content OR
- [ ] Pick an item then requesting a link to the content from the github repo by posting a request on this issue
- [ ] Review/assess/update that content and follow the RFC process for submission here

**Comment by ayliao** [comment]
These could be great good first issues, but how do we decide which articles (if any) we actually want to RFC and bring into the website? Do we just make PRs for each article and review them individually?

**Comment by keywordnew** [comment]
I'd lean towards individual PRs.

#105 was a massive PR with multiple sections, which was decided to be reviewed piecemeal once merged, partly because of the extra effort that would be needed to split up the PR.

But that content was comparatively up-to-date. [This content](https://github.com/nodejs/website-redesign/issues/nodejs.org/en/knowledge) under discussion needs to be checked for relevance.

Pinging @amiller-gh for guidance on how this review would fit into the RFC process.

**Comment by ayliao** [comment]
Yeah I was leaning towards individual PRs as well, since it seems a lot more manageable to review each article on its own for relevance and correctness.

p.s. I think your link may be broken, this is the page under question, right? [https://nodejs.org/en/knowledge/](https://nodejs.org/en/knowledge/)

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
