### ISSUE TITLE
Feature Request: Introduce search for docs

### ISSUE THREAD

**Issue by antstanley** [nodejs/website-redesign#130]
The Node docs site today do not have search. It would improve UX of the docs if search was introduced. 

Most major languages have search within their docs, for example Rust ([https://doc.rust-lang.org/std/index.html](https://doc.rust-lang.org/std/index.html)), and Go ([https://golang.org/](https://golang.org/)).  The Go website implements site wide search, which could be an interesting option for Node, as you could include how to guides and example apps into the search.

Today searching the docs either requires viewing them all as one page and using browser search, or using Google to do a site search, which isn't great either as you need to leave the docs page to do it.

There are a number of ways to implement search, and the options should be included in tech stack discussion on the new website. Happy to contribute to any discussions, and technical implementation.

**Comment by amiller-gh** [comment]
Note from todays meeting – we're going to do this! 🎉 Likely after API docs land in the site and we have content to test against. We'll pick this up once that happens 🙂

**Comment by amiller-gh** [comment]
Closing in favor of #257 🙏
