### ISSUE TITLE
Ping people interested in development as we begin the next phase

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#140]
People have been expressing interest in contributing to site development since we made an open call by adding themselves to the README. Let's give them a heads up as the development work begins.

https://github.com/nodejs/website-redesign#site-development

**Comment by mbj36** [comment]
Hey people, we have been going forward rapidly with  nodejs website prototype in another repo (https://github.com/nodejs/website-prototype) (Sorry if you were not aware of this repo)

I am calling out all people who have shown interest in development here (https://github.com/nodejs/website-redesign#site-development) to start looking at the issues in website-prototype repo, we have opened some `good first issue` , Feel free to comment on issue and start working on them 👍 

@abiclub23 
@ajay2507 
@connorholyday 
@iceagency-jakecruse 
@iceagency-lukehopkins 
@jestho 
@jonahmoses 
@sagirk 
@ollelauribostrom 
@belar 
@erichodges 
@utkarshbhimte 
@lidoravitan 
@ZanMarolt 
@imbhargav5 
@mikeattara 
@ZYSzys 
@mrjam2 
@jamesgeorge007 
@Yash-Handa 
@iNidAName

**Comment by amiller-gh** [comment]
🙏 ❤️
