### ISSUE TITLE
New Home: Nodejs.dev?

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#147]
We're currently split between two repos and it may make sense to consolidate 🙂 

The website-redesign group is owning development of `nodejs.dev`. For simplicity's sake, we may want to move our governance documents, meeting minutes, admin issues, etc over to https://github.com/nodejs/nodejs.dev and have a single source of truth.

I also see the value in keeping an admin-only repo for redesign administration live. However, wanted to breach the conversation and see what peoples' feelings on it are!

**Comment by keywordnew** [comment]
My initial thoughts about moving administrative activity into the nodejs/nodejs.dev repo is that downsides of mixing admin with a codebase and polluting the repo would outweigh a single source of truth. 

nodejs/website-redesign could be archived when the initiative reaches the maintenance stage, but until then I would suggest the existing division of concerns.

**Comment by amiller-gh** [comment]
If we’re going to keep them separate, let’s be sure to point between the two repos in the READMEs at least 🙂

And, rebuttal for the separation of concerns argument: the only real activity in this repo, especially since we migrated the source-of-truth `/documentation` directory to nodejs.dev, is in the `/minutes` directory. The only substantiative issues have been the auto-generated meeting issues. All other open issues and PRs are either old, or defunct and better housed in nodejs.dev. The majority of our past few recurring meetings have been spent addressing issues in nodejs.dev as well. I believe for newcomers arriving to the itiative it would be easier to follow all this rather co-dependent activity in a single place.

**Comment by keywordnew** [comment]
> If we’re going to keep them separate, let’s be sure to point between the two repos in the READMEs at least 🙂

From the meeting earlier today, that seems to be the best next action, based on the knowledge that ownership of future work will shift and governance has yet to be decided.

**Comment by jonchurch** [comment]
This was discussed again at the Berlin summit, and briefly on the WR meeting #168.
With small attendance, it was determined that combining the repos would be a good decision. 

But I can't say for sure it has been decided finally, as far as I know these recent conversations weren't held with a full quorum (unless the discussion at the summit counts!).

Personally, I'm in favor. As a new contributor, it is confusing having this work happening under two different repos. I think that tags and filtered searches can keep things from getting messy or cluttered in regards to issues and PRs.

I think that the people who are most likely to be negatively affected by these repos being in two different places are the people who are also most likely to be turned away by a confusing experience, new contributors.

**Comment by amiller-gh** [comment]
Had to unarchive the repo to remove the label and close this issue to get it off the agenda 😅 

Done!
