### ISSUE TITLE
What is the licensing for contributed content?

### ISSUE THREAD

**Issue by jonchurch** [nodejs/website-redesign#153]
I see the license was copied over from the Nodejs.com site in #151. 

The company I work for ([osiolabs](http://www.osiolabs.com)) is sponsoring my time to contribute to the redesign effort, and we are curious what happens to licensing for the content contributed here. I'm wondering if anyone can clarify a few things for me, and anyone else who comes along.

- **Is the license that is currently in effect informed by a standard one somewhere?**
- **Would we (contributors) be able to reproduce on our own properties the content we contribute to the Nodejs site, without carrying the permissive license?**

I ask because I Am Not A Lawyer, and there is good opportunity to contribute content we are already working on for ourselves, or will work on. I am unclear how the license currently in effect works in practice, hence this question.

I know @flaviocopes has contributed a lot of material already, and I'm curious if licensing under this sort of scenario  has been addressed yet.

**This isn't specifically a blocker for us, but a conversation I'd like to start.**

Thanks for ya'lls time!

/cc @eojthebrave @add1sun

**Comment by amiller-gh** [comment]
Very good conversation to start!

We’ve recently received some guidance on licenses for non-code content here: https://github.com/nodejs/community-committee/issues/271#issuecomment-471488180

Will parse through this in more detail in the AM, but we’ve been asked to license user focused content under CC-BY 4.0, which I believe allows for commercial and non-commercial re-use with attribution.

Pinging @brianwarner for confirmation.

**Comment by amiller-gh** [comment]
Also, welcome! Let me know how I can help get you up to speed to start contributing 🙂

**Comment by brianwarner** [comment]
Hi, yes, just confirming that this was the guidance provided by the Node legal committee.  Please note that there are a number of distinctions in the guidance, particularly in situations where the asset may be distributed with the code.
