### ISSUE TITLE
CFP for Collab Summit is live! Let's answer the Call for Proposals 📣

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#155]
Issue [#149](https://github.com/nodejs/summit/issues/149) in nodejs/summit has been opened, with a link for CFP submissions.

With all the work that's been done in website-redesign, it's worth doing a session to a) update others on progress and b) collaboratively land on steps for the next half year.

Y'all are amazing and it would be great to meet in-person ✨

**Comment by amiller-gh** [comment]
Resolution in meeting: we'll submit CFP! 🎉 @keywordnew to take 👍

**Comment by keywordnew** [comment]
We've submitted a CFP for a meeting. This is the proposed outline for our meeting at the Collab Summit:

Level-setting
* Pace of progress picked up quickly, would be good to see if we’re still functioning well
* Recap of the process so far and future plans.

Introduction to the machine and improve onboarding docs
* Workshop to get new people on board. We're not teaching React/Gatsby. We're teaching people about how we implemented nodejs.dev
* In the process improve onboarding docs
* Nice to have: Get good first issues in the issue queue and use as walkthroughs

Collaboration
* with core docs contributors: How we want to tackle API docs
* with i18n: How to best consume localized API docs"

**Comment by amiller-gh** [comment]
Its today! Getting started now 🙂We're treating this as an onboarding and sprint planning session.

**Comment by amiller-gh** [comment]
https://medium.com/the-node-js-collection/redesigning-nodejs-part-1-fac08a0e015a

**Comment by amiller-gh** [comment]
https://projects.invisionapp.com/share/KFNHXTOC4J6#/screens/281335816

**Comment by amiller-gh** [comment]
http://nodejs.dev

**Comment by amiller-gh** [comment]
🙏great session all! Closing since this is in the past.
