### ISSUE TITLE
Node.js Foundation Website Redesign Brief 2019-03-28

### ISSUE THREAD

**Issue by ogonzal87** [nodejs/website-redesign#157]
Hey team! 👋🏼

I am Oscar, and I will be contributing to the website redesign project. Adam is introducing me to the team tomorrow but before then, I wanted to send over a **working** [Google Doc](https://docs.google.com/document/d/1lC_BvVy0MCA73e-399Qyzn9Bhf9k4p4SnctHZqoI0q4/edit?usp=sharing) with questions I have that would help the redesign move effectively. Would be awesome if you can take a look at it and help me fill it out at some point. Some of the questions might seem obvious but I do not like to make any assumptions. Maybe some of these questions we could ask them via Twitter polling-style to involve the community in the design process. 

If you have any other questions for us to discuss during the meeting, feel free to add to the doc.

Thanks and looking forward to meeting you all.

**Comment by ahmadawais** [comment]
Welcome, Oscar! Awesome to have you here. 👏

**Comment by LaRuaNa** [comment]
Hi Oscar, nice to have you here :]

**Comment by BeniCheni** [comment]
Hi, I’ll try to dial in zoom or watch YouTube as observer tomorrow. And defly will participate the WG meetings more and contribute more to nodejs.dev in the future. Cheers~

**Comment by sagirk** [comment]
Hello Oscar! Welcome to the team! ❤️

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
