### ISSUE TITLE
Create data contract for how API documentation will be consumed

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#158]
We need a spike to find answers on:
* how we want to tackle API docs
* how to consume localized API docs. 

This issue is a stake in the ground to kick things off. We may need a dedicated meeting to get this going. It could even need to be recurring until the spike is complete.

Questions to resolve now:
* Should this meeting have its own time found using a Doodle or can we have it start at the end of an existing Node.js meeting?
* What should be on the agenda?

## Within the scope of this are:
* #76 Consuming localized docs from `nodejs-i18n` module
* [#4](https://github.com/nodejs/nodejs.dev/issues/4) Create an i18n spin out meeting to talk shop

@amiller-gh @LaRuaNa @zeke @sagirk @iNidAName @AhmadAwais @MaedahBatool @obensource

**Comment by inidaname** [comment]
My opinion

- Should this meeting have it own time: **Yes** it will give it the much need attention and speed to answer the questions raised
 - What should be the agenda: I feel kicking off the first meeting will create a road map for this plus the agenda could be prioritise around the scope mentioned.

> Within the scope of this are:
#76 Consuming localized docs from nodejs-i18n module
#4 Create an i18n spin out meeting to talk shop
#169 Navigation / Section Proposal

**Comment by amiller-gh** [comment]
Closing in favor of https://github.com/nodejs/nodejs.dev/issues/255
