### ISSUE TITLE
Node.js Foundation Website Redesign Initiative Meeting 2018-03-01

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#17]
Much of the agenda from the last meeting is preserved. #5 was removed, logistical reasons detailed in the issue. #15, #13, and #12 has been added (from developments related to TODOs from the past meeting. Progress, woop woop! 🚀). This can be modified as needed at the beginning of the meeting.

**Time**
----
**UTC Thu 01-Mar-2018 15:00 (03:00 PM)**

Or in your local time:

https://www.timeanddate.com/worldclock/fixedtime.html?msg=Website+Redesign+Meeting+2018-03-01&iso=20180301T15&p1=%3A&ah=1

**Links**
----
* **Minutes Google Doc:** https://docs.google.com/document/d/1vESSiffxpjbI5Chb6ZoJcF5kNdiZ7RQd_0g83V8wSGI/edit?usp=sharing
* **Previous Minutes Google Doc:** https://docs.google.com/document/d/1h3-YLjzeEZYKQQxscZUB44-jGmqFg4mwa0VO4VZb38Q/edit?usp=sharing

**Agenda**
(As we're still in early stage discussion, these items can be reordered by suggested importance)

* Website Wireframes #15
* Voice and Tone Guidelines #13
* Tech Exploration for In-Browser Node Playground #12 (related to, but not the same as, #9)
* Getting started with Node #9 
* Should We Attempt an Update of Official Node.js Messaging https://github.com/nodejs/community-committee/issues/242
* Content structure #4 
* Discussing a later meeting time for Western American timezones

**Invited Members**
----
- @oe - Olivia Hugger
- @fhemberger - Frederic Hemberger
- @bnb - Tierney Cyren
- @timothyis - Timothy
- @jestho - Jesper Thøgersen
- @JonahMoses - Jonah Moses
- @amiller-gh - Adam Miller
- @skllcrn - Christopher Skillicorn
- @pierreneter - Pierre Neter
- @emilypmendez - Emily Mendez
- @darcyclarke - Darcy Clarke
- @maddhruv - Dhruv Jain
- @obensource - Ben Michel
- @Fishrock123 - Jeremiah Senkpiel
- @chowdhurian - Manil
- @franciscop - Francisco Presencia

**Joining the meeting**
--
Zoom Meeting; a link will be posted here shortly before the meeting starts.

If you're interested in joining the meeting, just ask in the issue and we will invite you!

**Public participation**
--
We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ/live when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

**Comment by fhemberger** [comment]
Sorry, won't be able to make it this time. But I'll check the notes and give feedback.

**Comment by ghost** [comment]
Thanks @chowdhurian for making these, I'll probably PR our layout into the meeting agenda generator so we can generate these automatically.

**Comment by maddhruv** [comment]
@chowdhurian the website is showing an error with time.
Please check the time and date

**Comment by keywordnew** [comment]
@maddhruv I'm not able to see the error :( Is it still happening for you? This is what I see:

<img width="341" alt="screen shot 2018-02-28 at 16 39 15" src="https://user-images.githubusercontent.com/10335475/36821085-124e9b8e-1ca6-11e8-8e6d-ef89d65a5fb7.png">

**Comment by maddhruv** [comment]
@chowdhurian no errors now!
Don't know what was happening before

**Comment by darcyclarke** [comment]
@chowdhurian Do you send out (via email or other means) an invite beforehand to join the livestream? I'm catching up as I wasn't able to make the first two meetings.

**Comment by bnb** [comment]
@darcyclarke usually we post an issue here and a Zoom link right beforehand (I'm just about to post it).

**Comment by bnb** [comment]
Join link for today's meeting: 

https://zoom.us/j/431151994

**Comment by bnb** [comment]
Also, I'd like to add as an agenda item that we discuss a later time for the members who are interested in participating but are on the Pacific coast in North America.

**Comment by mrhinkle** [comment]
I couldn't attend the beginning of the meeting and caught up via YouTube. I saw the request for access to website traffic history.  I think we can easily provide website traffic access via Google Analytics. Also, I plan to try to attend as my schedule allows I think this is a great initiative and much needed. Feel free to direct any resource requests from the Foundation to me as needed.

**Comment by keywordnew** [comment]
@oe I hope this is ok for us to use next time.

https://github.com/nodejs/make-node-meeting/pull/34

**Comment by ghost** [comment]
@chowdhurian this helps a lot, thanks!

**Comment by trivikr** [comment]
Can someone add meeting notes from [doc](https://docs.google.com/document/d/1vESSiffxpjbI5Chb6ZoJcF5kNdiZ7RQd_0g83V8wSGI) to [meetings](https://github.com/nodejs/website-redesign/tree/master/meetings) folder?

**Comment by ghost** [comment]
Notes: https://github.com/nodejs/website-redesign/blob/master/meetings/2018-03-01.md
