### ISSUE TITLE
Coordinating "Getting Started" content with NodeSchool content

### ISSUE THREAD

**Issue by ghost** [nodejs/website-redesign#18]
As we discussed in our latest meeting, it would be super cool to be able to coordinate content for a potential "getting started" page together with some folks who are involved in NodeSchool maintenance. Having to write a lot of content from scratch isn't the best thing, and because NodeSchool is specifically targeted at newcomers, I think this would be a good place to collaborate.

**Comment by ghost** [comment]
Some people that I know are involved in NodeSchool content/organizing: @jpwesselink @watilde @substack. If anyone is interested in working something out for this, please let me know!!

**Comment by maddhruv** [comment]
Hey @oe I am interested!

**Comment by emilypmendez** [comment]
I am also interested @oe !

**Comment by keywordnew** [comment]
The NodeSchool workshoppers would indeed be a good gateway into Node through the Getting Started page. Your local NodeSchool events could serve as an easily accessible, in-person, distributed resource for anyone trying out Getting Started content. 

With the workshoppers potentially being part of the new Getting Started page, some of the work here may involve updating them.

**Comment by keywordnew** [comment]
cc @Qard

**Comment by bnb** [comment]
Per today's Website Redesign Initiative meeting, we'd like to see if we can get a secondary meeting with a few of the NodeSchool organizers/maintainers to discuss this.

@oe @jpwesselink @watilde @substack would y'all be willing to meet with us at some point to have a focused discussion on this?

**Comment by ghost** [comment]
@bnb Sure, sounds good from my side.

**Comment by watilde** [comment]
Hello! Yeah, I'd love to work on this together. I wonder what we possibly can put useful information on nodejs.org more than just a link.

I will subscribe this issue anyway :)

**Comment by add1sun** [comment]
Heyo, I'd also like to help out with this if I can. I'm also curious if any of you all will be at the Berlin Collab Summit (https://github.com/nodejs/summit/issues/60).

**Comment by Qard** [comment]
I'll be at the collab summit, and I'd love to chat about how to integrate NodeSchool things with Node Foundation and the website redesign, assuming I can find some time. 😅

**Comment by maddhruv** [comment]
We plan to collaborate fetching/contributing getting started, how to, articles and some other contents with NodeSchool people for the new website we are planning so that it is faster and healthier to for you to get up!

**Comment by maddhruv** [comment]
Also as proposed in #31 we can add members from NodeSchool to the CMS/API service we shall be using, so as it will become easier coordinating content with them.

**Comment by maddhruv** [comment]
What topics should we be covering under Getting Started section for the website?
Thoughts?

**Comment by JonahMoses** [comment]
related #39

**Comment by keywordnew** [comment]
Closing this thread for now, as we've got quite a bit cooking with the knowledge base articles.

Feel free to reopen if needed.
