### ISSUE TITLE
Language standard of the current website

### ISSUE THREAD

**Issue by maddhruv** [nodejs/website-redesign#19]
The current website's language and documentation are so harder for a nubiee to be easily understandable.
Like use terms from JS and CS (Computer Science) are not so fancy for a new user for nodejs.
I suggest implementing and using a much easier and friendlier language on the website.

**Comment by maddhruv** [comment]
Closing the issue for no further discussion

**Comment by amiller-gh** [comment]
Language complexity issues like these will likely be addressed in the Voice and Tone PR 👍 

https://github.com/nodejs/website-redesign/pull/14

I expect we'll pay close attention to over-use of jargon when we finally start drafting content.

**Comment by keywordnew** [comment]
Thank you for bringing this issue to the initiative's attention 💯

The language in documentation being very technical is **definitely** a pain point for people using the documents. I believe the metrics for the nodejs.org website reflect this. FWIW recent conversations with users (though anecdotal) also reflect this.

+1 to addressing this with recommendations for more accessible language through Voice and Tone guidelines
