### ISSUE TITLE
Identify topics to discuss for Collab Summit Spring 2018

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#29]
Agenda building for [Collaborator Summit Berlin 2018](https://github.com/nodejs/summit/issues/60) has begun!

The Summit will have many of our current active collaborators. My experience from joining the last Collaborator Summit in Vancouver at Node.js Interactive suggests that raising the profile of this initiative there would help us get around blocks we may be facing now (and in the future) by taking the opportunity to connect with people/groups outside this redesign initiative.

Let's come up with: 🙌
* topics we should cover there
* tangible goals we'd like to have met

To get us started:
* #18 involves coordinating "Getting Started" content with NodeSchool content. Several people, both from within the project and without, plus a few from NodeSchool expressed interest in participating during the Summit.

**Comment by chowdhurian** [comment]
To get this moving, I'd like to add this to the agenda for #30.

**Comment by bnb** [comment]
- Getting Started

**Comment by amiller-gh** [comment]
+1 on getting started. We may also want to iterate on "marketing speak" for the homepage in that same working session as well.

@bnb, I remember you commented [https://github.com/nodejs/summit/issues/60#issuecomment-369325534](here) that you wanted to see high-level reports on CommComm initiatives to the larger org. Since Manil and I will both be in attendance, would you also like us to prepare that report for the Website Redesign committee?

**Comment by add1sun** [comment]
Hey all, over in the main summit thread, we are compiling a list of topics for presentation. Currently this one isn't listed. I think we should definitely have the Website Redesign in there, but I don't want to volunteer others. :-)

https://github.com/nodejs/summit/issues/60#issuecomment-383570223

**Comment by keywordnew** [comment]
Thanks for the update @add1sun! 🙌🏽 I agree it would be immensely helpful for us to have Website Redesign in there.

From [comments](https://github.com/nodejs/summit/issues/60#issuecomment-383570223), we could explore a relationship with i18n efforts.

**Comment by amiller-gh** [comment]
Just commented on the main thread and volunteered us to lead a session 🙂 Lets coordinate what that will involve, and start to prep the presentation, on this ticket 🎉

**Comment by keywordnew** [comment]
Closing as this has passed!

**Comment by amiller-gh** [comment]
🎉
