### ISSUE TITLE
Node.js Foundation Website Redesign Initiative Meeting 2018-02-01

### ISSUE THREAD

**Issue by ghost** [nodejs/website-redesign#3]
## Time

**UTC Thu 01-Feb-2018 15:00 (03:00 PM)**

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Website+Redesign+Meeting+2018-02-01&iso=20180201T15&p1=%3A&ah=1

## Links

* **Minutes Google Doc**: https://docs.google.com/document/d/1upCQqRI6BxClP6or1mvaQSVSXakzEEzWVStsnboqbVo/edit?usp=sharing
* **Previous Minutes Google Doc**: nil

## Agenda

(These items can be reordered by percieved importance)

* General objectives, strategy going forward
* Overall site structure
* Addressing content held in separate repositories
* Synching with the Node.js Foundation website
* Missing requirements?
* Decision structure (consensus, etc.)
* Previous attempts at redesigning the website

## Invited Members

- [@oe](https://github.com/oe) - **Olivia Hugger**
- [@fhemberger](https://github.com/fhemberger) - **Frederic Hemberger**
- [@bnb](https://github.com/bnb) - **Tierney Cyren**
- [@timothyis](https://github.com/timothyis) - **Timothy**
- [@jestho](https://github.com/jestho) - **Jesper Thøgersen**
- [@JonahMoses](https://github.com/JonahMoses) - **Jonah Moses**
- [@amiller-gh](https://github.com/amiller-gh) - **Adam Miller**
- [@skllcrn](https://github.com/skllcrn) - **Christopher Skillicorn**
- [@pierreneter](https://github.com/pierreneter) - **Pierre Neter**
- [@emilypmendez](https://github.com/emilypmendez) - **Emily Mendez**
- [@darcyclarke](https://github.com/darcyclarke) - **Darcy Clarke**
- [@maddhruv](https://github.com/maddhruv) - **Dhruv Jain**
- [@obensource](https://github.com/obensource) - **Ben Michel**
- [@Fishrock123](https://github.com/Fishrock123) - **Jeremiah Senkpiel**
- [@chowdhurian](https://github.com/chowdhurian) - **Manil**
- [@franciscop](https://github.com/franciscop) - **Francisco Presencia**

## Joining the meeting

Zoom Meeting; a link will be posted here shortly before the meeting starts.

If you're interested in joining the meeting, just ask in the issue and we will invite you!

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

**Comment by ghost** [comment]
The exact time for this meeting is preliminary, and can be changed in case more members will be able to attend.

**Comment by bnb** [comment]
I will be traveling and will work on making time to attend (shouldn't be a major issue), but if I'm not we should likely find someone else to create/run the Hangout on Air or Zoom session. Not sure if @mhdawson or @hackygolucky would be able to.

**Comment by Trott** [comment]
> A standing invitation exists for all @nodejs/tsc and @nodejs/community-committee members who are not also CommComm members 

Is this supposed to say `Website WG members` instead of `CommComm members`? Presumably, all members of @nodejs/community-committee are CommComm members...

**Comment by ghost** [comment]
@Trott oh, whoops. forgot to edit that when I copy-pasted

**Comment by obensource** [comment]
I'm not on the invited members list, but I did receive a notification–I'd love to join if that's cool? 😎

**Comment by ghost** [comment]
@obensource sure! I'll add you to the list.

**Comment by obensource** [comment]
@pup wahoo! Thanks. :D

**Comment by Fishrock123** [comment]
> A standing invitation exists for all _x_, _y_, _z_ **in observer capacity** ...

Uhhhh It's not like there is any official governance, and there's no difference for people raising their hands here or in https://github.com/nodejs/nodejs.org/issues/1534

maybe the language should be changed and um, not copied from a _committee_ meeting

Anyways I'd like to be invited too

**Comment by ghost** [comment]
@Fishrock123 you're right, sorry. almost all of the people who raised their hand in the nodejs.org issue are part of the initial team here though

**Comment by keywordnew** [comment]
I'm getting up to speed with how things are done here, but I got a notification, and I'd like to join the meeting to see how I can contribute.

**Comment by franciscop** [comment]
Hi @pup, could I be invited as well please?

**Comment by albinekb** [comment]
I'll contribute if you choose React. It just makes it so much easier because it's a predefined way to work with everything. It's hard for me to contribute to the current website because the setup is very foreign to what we do day-to-day.

**Comment by timothyis** [comment]
Depending on what the scope is, it might not be a bad idea to incorporate React via Next.js for server-side rendering. Shows the power of node! We can discuss this when the time is right though.

**Comment by maddhruv** [comment]
hey @oe Please post the concerned links of the meetings - Doc, Zoom

**Comment by ghost** [comment]
@maddhruv Added the Google Docs link to the original post, the Zoom link can't be shared until right before the meeting starts.

**Comment by bnb** [comment]
@oe I added the event to the calendar, fwiw: https://nodejs.org/calendar

**Comment by franciscop** [comment]
The meeting is in exactly 24h, right? I think I got a bit confused (it is 00:00 in my timezone).

**Comment by ghost** [comment]
@franciscop Yep!

**Comment by obensource** [comment]
Hi all. I came down with a high grade fever and cold overnight and will unfortunately not be able to join today's important meeting. 😔

The gist of things to share about i18n for the site redesign effort is: 

If we receive overwhelming adoption from localization groups we will be working on providing y'all with a module to import by which you can choose what locale to load based on the UI interaction of native language selection.

I hope to get a sense of your working timeline so we can have a general shipping time in mind as well. 

I'm really looking forward to reading the notes. Ping me if you need, and sorry I can't be there!

**Comment by ghost** [comment]
@bnb are you available? if so, could you set up the zoom thingy?

**Comment by bnb** [comment]
@oe yes one sec

**Comment by bnb** [comment]
Join link: https://zoom.us/j/212488219

**Comment by ghost** [comment]
Closing.
