### ISSUE TITLE
Potentially using an API service for website content

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/website-redesign#31]
Hey All,

One form of friction with the current website has been the ability for the foundation team to easily add content. Apologies in advance if this has been discussed elsewhere but I wanted to suggest utilizing a service such as https://www.contentful.com/. Contentful is a CMS, but only for content. It exposes an api that any website, including statically generated sites, can consume. This approach would allow both the website and foundation teams to maintain velocity where they need it.

There are likely other service providers, but contentful came recommended from a creative agency who has had to deal with similar friction / velocity issues in the past.

Thoughts?

**Comment by amiller-gh** [comment]
I really like this idea and want to keep it top-of-mind once we dive into site implementation details 👍 

We do something similar for my team's Design Systems documentation site here at LinkedIn – it works very well to help keep content fresh.

WebHook is another content API service to look in to: http://www.webhook.com/

**Comment by add1sun** [comment]
Hi there, I just wanted to chime in that, while not a SaaS, there is an open source equivalent of this with Drupal (using [Contenta](http://www.contentacms.org/) or [Reservoir](https://github.com/acquia/reservoir)). The Drupal community is very bullish on this model and I think we could find good support from the Drupal community to help with setup and improvements that would be a good back and forth that helps both Node and Drupal.

If you are interested in learning more about it and sorting out who can come speak about it on the Drupal side, I can definitely make some introductions.

**Comment by fhemberger** [comment]
When using Contentful, the costs for 10 locales would be $879/month. Do we have a budget for this? Also managing many pages/content blocks in Contentful is IMHO a bit inconvenient, because you only have a flat hierarchy.

I don't know if this is necessary. With the move of the Foundation pages to a separate website, there weren't any content changes on the main website any more. Or was your intention to use such an API to power both websites in the future?

**Comment by bnb** [comment]
+1, we use Contentful at NodeSource and it's a pretty great experience. They also use Node.js on the back-end 😅

In today's meeting we discussed this, but generally agreed that this should _probably_ be decided upon once we're beginning to implement the design that we end up with.

That said, context and commentary is super appreciated in this issue ♥️

**Comment by JCMais** [comment]
Has this moved forward / been discussed lately?

There are some content being translated using Crowdin already available on i18n repo

**Comment by ZanMarolt** [comment]
There is also an open source alternative called [Strapi](https://strapi.io/). Built on top of Node.js as well 😉. It is very flexible (you can define the fields yourself) on what content you want to store. It works very well with Gatsby.js which we decided to use.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
