### ISSUE TITLE
New Website Redesign Initiative Champion(s)

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#36]
@oe is [stepping down as initiative champion](https://github.com/nodejs/community-committee/pull/290#issuecomment-380915380) 😢 

So we get to determine who will serve as the next!

Current state of things: @maddhruv had expressed interest directly to @oe earlier, but was unable to attend the April 12th meeting where we briefly discussed succession. In that meeting, @chowdhurian and I were self-nominated to serve as co-champions.

Because not everyone was in attendance, we should continue discussion before making a choice 🙂 

> **Disclaimer:** I'm not sure what the precedent is here! @bnb or @oe may be able to comment.

**Comment by ghost** [comment]
I believe this is the first time this has happened in this form, so I don't think we need to follow any specific rules here! Something more direct that doesn't require a vote would be nice :P

**Comment by maddhruv** [comment]
Like I am having my final exams these days, I can't dedicate much time to any other stuffs! Neither do I work for my intern or even touch my laptop/PC.
I am upset I couldn't attend today's meeting, but will definitely check the YouTube stream/recording and minutes too!

**Comment by maddhruv** [comment]
I am very excited with the Website Redesign Initiative with NF and also this is the landing project I had with NF, shown concern to @oe today about the startegy and feel I am healthy with the job!

**Comment by maddhruv** [comment]
NP if @amiller-gh or @chowdhurian take over :heart_eyes:

**Comment by amiller-gh** [comment]
Thank you @maddhruv! A nice easy resolution 😄 

Best of luck on the final exams!!! 💯

**Comment by maddhruv** [comment]
But like I wasn't present in the meeting but am interested in joining hand too! As a co-/champion :heart_eyes:
Not going offensive with you and manil here!
