### ISSUE TITLE
Node.js Extended Color Palette 

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#42]
Hi all!

I'm back in business after disappearing for a couple crazy week after an OSS launch here at LinkedIn – excited to keep pushing things forward 🎉 

As we've discussed in both the Badges WG, and in meetings for this WG, we're going to need an extended color palette (one part of a more detailed Node.js Design System we need to establish) to help keep consistency between all the new design projects the CommComm is spinning up – especially if/when we start getting more design contributions from across the community. This is especially important for the Website Redesign WG since we're hoping to kick off a larger visual design phase soon, as we discussed in the previous meeting.

So, having some experience in color theory and design systems development, here is my proposal: 

https://medium.com/@ammiller/redesigning-nodejs-org-584212bb25e1

(Seriously, be sure to read the Medium post – it contains a lot of rationale and process 😉)

![nodejs-color](https://user-images.githubusercontent.com/7856443/39725320-29b416a2-5200-11e8-8dc7-a50df53fac84.jpg)

Outstanding questions I see:

  1. What is / will be the CommComm's process for approving / adopting design system changes like this?
  2. Most design system changes we make won't effect brand related material, this one does. (In a very limited way, and for very good reasons – read the post!) Does this introduce any other considerations for adoption?
  3. The solution uses an open source color library as a foundation for its design. Does this introduce any other considerations for adoption?
  4. What do you think of the extended color palette solution as a whole? I love hearing feedback on design theory and brand alignment, please share your thoughts freely ❤️

**Comment by SMotaal** [comment]
@amiller-gh I have a quick question regarding color space and color consistency. From my understanding, like HSL, HSB is a device dependent color space. What are the reference device conditions for those values (color profile, display used... etc.)?

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
