### ISSUE TITLE
Node.js Typography Spec

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#43]
In preparation for an open call for designers to contribute, we need to lock down some foundational design elements to help keep a degree of Node.js brand consistency between high fidelity mocks.

Delivering a comprehensive typography spec will be an import part of this Node.js Design System.

**Comment by amiller-gh** [comment]
Material design is a solid example of an effective typography spec: https://material.io/design/typography/the-type-system.html#type-scale

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
