### ISSUE TITLE
Node.js Grid and Spacing Spec

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#44]
In preparation for an open call for designers to contribute, we need to lock down some foundational design elements to help keep a degree of Node.js brand consistency between high fidelity mocks.

Delivering a comprehensive grid and item spacing spec will be an import part of this Node.js Design System.

**Comment by codeekage** [comment]
we could also use a wr-agenda on this

**Comment by maddhruv** [comment]
I am working on a responsive grid layout in css with flexbox.
Will complete it by the end of this month.

If we can use that on the website too.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
