### ISSUE TITLE
Node.js Website Design Systems Packet

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#46]
In preparation for an open call for designers to contribute, we need to lock down foundational design elements to help keep a degree of Node.js brand consistency between high fidelity mocks.

The designer getting started packet should include all Design System guidance from #45, #44, #43 and #42 (and any other design systems tickets that emerge).

For now, this can just be a collection of READMEs (or a PDF?) with DS guidance, although we may want to provide seed projects for Sketch and Illustrator. Ideas for how best to present this information until we can integrate it with the website are encouraged!

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
