### ISSUE TITLE
Components library

### ISSUE THREAD

**Issue by maddhruv** [nodejs/website-redesign#5]
I suggest building a component's library so that it would be easier and reliably maintaining the same feel over the whole website and hence eliminating the concern discussed in the meeting.
Just like how Google uses the same principles and _Polymer_ to build their whole Developers websites and API Documentations.

**Comment by jestho** [comment]
If we were to go for React I would suggest using [storybook](https://github.com/storybooks/storybook). Works more or less out of the box, provides a great dev experience, and is fairly customisable.

**Comment by ghost** [comment]
Taking this off the agenda for now as we explicitly chose not to focus on this during the initial stage of conception.

**Comment by amiller-gh** [comment]
Going to close this for now for ticket cleanliness sake until we start the technical exploration process post Node+JS Interactive 🙏
