### ISSUE TITLE
(Re)design related issues on nodejs/nodejs.org

### ISSUE THREAD

**Issue by fhemberger** [nodejs/website-redesign#58]
I've created a label for all open issues related to design and content discussions:
[nodejs/nodejs.org/issues#label:external/website-redesign](https://github.com/nodejs/nodejs.org/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3Aexternal%2Fwebsite-redesign)

It would be great if we could incorporate them in our redesign process (at least giving them a Yay or Nay).

**Comment by keywordnew** [comment]
Thank you for creating the label. It will make the transition more seamless.

I would note that this could expand the scope of the redesign and we need to be careful of what we pull in.

Overall, this is great. Several of these issues from nodejs/nodejs.org could be pulled into existing issues being discussed in this website-redesign repo.

**Comment by fhemberger** [comment]
A couple of those issues are worth discussing. And as some are already a bit older, a simple "No, we won't do that" or "We came up with a different approach" are totally fine as well.

There are also some technical discussions, which we don't need to address right away.

**Comment by amiller-gh** [comment]
Much appreciated! Happy to see that a lot of this is already on our radar 🙂Will go through and comment on each ticket in the next 24 hours.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
