### ISSUE TITLE
Show appreciation/thank you for security researchers whom are active in Node.js 3rd party modules bug bounty program

### ISSUE THREAD

**Issue by lirantal** [nodejs/website-redesign#59]
Following-up on @amiller-gh here https://github.com/nodejs/security-wg/issues/293#issuecomment-398166350

I'd like to propose that we also take into account in the new website's `Thanks` page an area where we can show appreciation for leading bug hunters and security researchers who take part in the bug bounty program that the Security WG's established for Node.js's 3rd party modules.

It was raised as part of our evangelism processes as well as showing appreciation to the volunteers who help secure the ecosystem and send us security reports for vulnerable modules.

**Comment by fhemberger** [comment]
FYI: There has also been the discussion to have a "thank you" page for hardware sponsors for our build environment. Although those are separate topics, maybe it does make sense to have a similar approach in both cases.

Ref:
- https://github.com/nodejs/nodejs.org/issues/1257
- https://github.com/nodejs/build#infrastructure-providers

**Comment by amiller-gh** [comment]
I envision this page to be under the still-un-wifreframed "community" section of the site 🙂Presumably we'll have a "Hall of Fame" or "Node.js Superstars" page where we'll thank all these contributors / sponsors. (Would love some kind of fun name for it – any other ideas?)

**Comment by keywordnew** [comment]
Nodemon-stahs. 🦄

**Comment by keywordnew** [comment]
Closing as the original issue [was closed](https://github.com/nodejs/security-wg/issues/293#issuecomment-411874662).

Feel free to reopen if needed!
