### ISSUE TITLE
Walkthrough in CommComm and TSC meeting?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/website-redesign#66]
Would it be a good time to do a walkthrough in the regular CommComm and TSC meetings (Say 10-15 mins) to bring people on progress up to date?  Talking with @bnb it sounds like we have a pretty good pictures of the new structure etc.

**Comment by mhdawson** [comment]
If the answer is yes, I'd suggest we schedule for one of the meetings following the week of Node Summit, so 2-3 weeks out.

**Comment by keywordnew** [comment]
To clarify, a walkthrough is a summarized overview of progress?

**Comment by amiller-gh** [comment]
@mhdawson, would love to schedule this for Wednesday the 26th's TSC meeting 👍 

Can use it as a preview / RFC of what we want to present at Node+JS Interactive, and as a CTA for docs content ideas.

**Comment by keywordnew** [comment]
To add to the comment above, CommComm typically gets regular updates at the bi-weekly meetings, so scheduling for just the TSC sounds ok.

**Comment by keywordnew** [comment]
As the Vancouver 2018 Collab Summit has just passed and contributors got an update there, we're postponing till the Jan 23rd TSC meeting.

**Comment by keywordnew** [comment]
Closing for now, feel free to reopen if a walkthrough is wanted!
