### ISSUE TITLE
Consuming localized docs from `nodejs-i18n` module

### ISSUE THREAD

**Issue by zeke** [nodejs/website-redesign#76]
There's a discussion under way at https://github.com/nodejs/i18n/pull/133#issuecomment-406091145 about how to design a module that can be consumed by the likes of this repo. Please weigh in over there (or here) with your ideas and any problems you see with the current leveldb-based module API I've proposed.

**Comment by keywordnew** [comment]
Thank you for bringing this up zeke.

This could be discussed at the upcoming meeting.

**Comment by keywordnew** [comment]
The proposed i18n module was discussed at [the last meeting](#79). The module would be a welcome tool.

We'd like to know what we could do to prepare to use it.

**Comment by zeke** [comment]
@chowdhurian that's great to hear! Knowing that it would be a welcome tool is encouraging. I'll try to find time soon to finish implementing a working version and publish it to npm.

**Comment by zeke** [comment]
@chowdhurian are there notes or a recording from the meeting? Would love to know if anyone had specific feedback or questions about the proposed i18n module or i18n stuff in general...

**Comment by bnb** [comment]
@zeke I _believe_ this is the video, though it could be the one before it: https://youtu.be/Kw96FO2p-sM

**Comment by amiller-gh** [comment]
Status: @zeke to shoot out a Doodle to get an i18n breakout session going for next week 🎉 We'll talk shop and hopefully get a path forward here.

**Comment by amiller-gh** [comment]
@zeke – thread bump 🙏

**Comment by obensource** [comment]
@amiller-gh @zeke @keywordnew @bnb @sagirk – started a doodle [here](https://doodle.com/poll/y3zu3ame6n6r4n77). If none of these times work let me know! 😎

🎉🎉🎉

**Comment by amiller-gh** [comment]
Closing this 🙏https://github.com/nodejs/nodejs.dev/issues/254
