### ISSUE TITLE
JS Interactive Community Corner Topics / Ideas for Website Redesign

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#80]
Go!

**Comment by jennschiffer** [comment]
i hear from all sorts of folks (teachers, students, pro devs) about how there are always gaps in education around various tools. lots of "hello world" and full-featured apps, but not a lot of in between. i'd explore ways of finding out what gaps there are with regards to using node during the community corner.

**Comment by keywordnew** [comment]
[The Call For Proposals thread for Community Corner](https://github.com/nodejs/summit/issues/103) 💁🏽‍♂️

**Comment by bnb** [comment]
@jennschiffer yeesssssssssss. That's 100% the hardest thing, and that would make a fantastic session/space.

**Comment by chowdhurian** [comment]
@jennschiffer would you be down to do a panel with @amiller-gh and I for the the Community Corner at N+JSI?

The first of the two topics below may speak to [your point above](https://github.com/nodejs/website-redesign/issues/80#issuecomment-413590775) about tackling the missing educational link between full-featured app guides and basic "hello world" tutorials.

We've yet to nail down a topic, so over the next few weeks, we'd likely want to get on a call and find our groove.

_These topics are suggestions to get the conversation rolling. Y'all please feel free to add and/or remix_

Brainstorming:
* an audience-participation segment exploring of the gaps in education around various tools. We'll ask questions that we'll prepare ahead of time to guide the conversation. Hopefully it can be recorded.
* the connection between building blocks of technology's "landing" page and successful adoption of the technology it represents: let's find the **minimum viable documentation**

**Comment by keywordnew** [comment]
@jennschiffer would you be down to do a panel with @amiller-gh and I for the the Community Corner at N+JSI?

The first of the two topics below may speak to [your point above](https://github.com/nodejs/website-redesign/issues/80#issuecomment-413590775) about tackling the missing educational link between full-featured app guides and basic "hello world" tutorials. 🐣

We've yet to nail down a topic, so over the next few weeks, we'd likely want to get on a call and find our groove.

_These topics are suggestions to get the conversation rolling. Y'all please feel free to add and/or remix_ 💯🎸💯

Brainstorming:
* an audience-participation segment exploring of the gaps in education around various tools. We'll ask questions that we'll prepare ahead of time to guide the conversation. Hopefully it can be recorded.
* the connection between building blocks of technology's "landing" page and successful adoption of the technology it represents: let's find the **minimum viable documentation**

**Comment by keywordnew** [comment]
@amiller-gh related to the conversation on this at yesterday's meeting, I can't remember if you said you have doc with content for this 🙂
