### ISSUE TITLE
Collab Summit: Website Redesign Breakout Session

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#88]
> Stub ticket for tracking, will be filled out soon.

# Motivation

# Agenda
TBD

**Comment by sagirk** [comment]
> Follow issue

<h6>A placeholder comment so GH keeps me notified of the conversations here.</h6>

**Comment by keywordnew** [comment]
Notes!

https://docs.google.com/document/d/16eRahz4dmoEBCyISoRr721Rg9gjCEXVRKVsz0RvxcUw/edit?usp=sharing

**Comment by sagirk** [comment]
Slides!

https://docs.google.com/presentation/d/1kHsqeQxg1lxWUvz4pVENsK9wY4FFFzeUORD-UwYfrNo

**Comment by amiller-gh** [comment]
Closed!  

🎉
