### ISSUE TITLE
Getting started with node

### ISSUE THREAD

**Issue by maddhruv** [nodejs/website-redesign#9]
Adding new sections to the *Getting Started* - 
- Learn Node (documentation for setting up node, beginning a node project)
- Various communities, summits, fests, confs nearby
- Publish your own node packages
- a tutorial guide (like what DigitalOcean has) on how to do this, etc
- Contribution guidelines to various projects/repo under Node.js foundation

I propose this idea for the new website.

**Comment by jestho** [comment]
I would really like to see a "try in your browser" REPL-thingy. Would fit into the Getting Started section, but also on the front/landing page.

(Although I see the irony in running server-side JavaScript in the browser 😅)

**Comment by amiller-gh** [comment]
I love the in-browser playground idea, most of the best docs sites out there let you try out their languages/frameworks in-browser! (Scala, Go, React, etc...)

Are there existing solutions we could use for an in-browser Node REPL?

**Comment by amiller-gh** [comment]
Glot.io is open source and provides an API: https://glot.io/snippets/exf503wqxt

**Comment by amiller-gh** [comment]
Typically, sites will provide a "Learning Paths" style tutorial or education page section on their site:

---

<div style="display: flex; flex-direction: row;">
<img src="https://user-images.githubusercontent.com/7856443/36079002-0314b318-0f33-11e8-8823-5aa08f9d2d3d.png" width="30%" />
<img src="https://user-images.githubusercontent.com/7856443/36079003-054fa4d0-0f33-11e8-835f-429947c7c0fb.png" width="30%"/>
<img src="https://user-images.githubusercontent.com/7856443/36079005-06bf1fc6-0f33-11e8-96dc-dd30b78c2a11.png" width="30%"/>
</div>

---

It would be great to offer content in this format for learning the basics of Node.js development. Is there an existing curriculum out there we can use as a foundation for the new Getting Started learning path?

**Comment by ghost** [comment]
You can find useful Getting Started guides [here](https://nodejs.org/en/docs/guides/).

**Comment by darcyclarke** [comment]
Hey folks!

Apologize I'm late to the game here (wasn't able to make the meeting last week). I think the playground idea is perfect for helping guide new folks along. I've been playing with [Runkit](https://runkit.com/home) for awhile and was going to use it on Toronto's NodeSchool site to help people immediately try out some of the code we are teaching them. Again, this kind of in-browser runtime environment should probably be supplementary to more standard written documentation/guidelines as mentioned above.

I think one of the questions/concerns I'd have for running with **glot**, specifically, is that it looks like it's not actively maintained (I could be wrong though).

**Comment by maddhruv** [comment]
For the **Getting Started** - learn Nodejs, new to nodejs
we can refer to the repo - https://github.com/nodejs/getting-started and can also invite content writers to make us easy to understand and more accurate contents for the Getting Started section

**Comment by bnb** [comment]
Going to remove the agenda label from this, since it seems there's been no further discussion or progress since the last meeting 👍

**Comment by maddhruv** [comment]
closing in context with #18
