### ISSUE TITLE
We need a .gitignore 👩🏽‍💻👨🏽‍💻

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#94]
We need to making git ignore a common hidden file on MacOS.

I noticed PRs were accidentally committing those.

The following needs to go into a .gitignore in the root of the project.

```
# General
.DS_Store 
```

**Comment by maddhruv** [comment]
perhaps
```thumbs.db```
generated on windows systems

**Comment by keywordnew** [comment]
@maddhruv curious if `thumbs.db` continues to show up past Windows 7?

**Comment by erichodges** [comment]
@chowdhurian I'm interested in helping. Maybe I could add the .gitignore? If so, I don't know where the repo is to add it. This one just seems to have docs etc. :-)

**Comment by keywordnew** [comment]
@erichodges it's yours if you want it 👍🏽

I can confirm, the file will go in root of this repo.

**Comment by erichodges** [comment]
Ok, cool! I'll fork/clone/PR.

Do you guys want anything more than .DS_Store and maybe .env?

Ok, the PR is ready.

It would be cool to get on the redesign Site Dev team if possible. :-)

**Comment by JonahMoses** [comment]
@chowdhurian some searching around leads me to believe `thumbs.db` do continue to show up past Windows 7. 

Here's some one describing how to reveal them in Windows 7, 8 and 10:
https://www.pcworld.com/article/2999243/windows/manage-thumbs-db-files-in-windows-and-on-the-network.html

**Comment by keywordnew** [comment]
Closing this issue, as it's been addressed by PR #96.
