### ISSUE TITLE
Idea: Host Docs Hackathons

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#99]
As we begin to build out documentation more, it may be helpful to host regular "Docs Hackathons" where we can get groups together to collaborate on new documentation content.

Format, location, hosts, etc TBD – we can brainstorm here.

**Comment by keywordnew** [comment]
I'll preface this suggestion with the comment that formats are something we can def hone over time. 

Length-wise, I've found 4 hours to be a good length for letting people hack away and dive into details if it comes up.

On the subject of hosts, I've found 1 mentor to 4 new contributors is a ratio where no one person is too overloaded.

Looping in @qard for visibility and more experience; we collaborated on the first docs ad-hoc hackathon in Vancouver.

**Comment by Qard** [comment]
Yeah, we've been doing a regular open source day at NodeSchool Vancouver. It might be a good idea to approach other NodeSchool locations about duplicating that effort and using it to focus lots of attention on the docs. Beginner and intermediate experienced folks are the best for contributing to the docs because they would have the best understanding of its deficiencies.

**Comment by eojthebrave** [comment]
Spending some time up-front defining an outline of what needs to be written might help make it easier to have sprints be productive. Especially if you can break the outline up into more bit-sized chunks. I imagine anyone new that needs to first familiarize themselves with the voice, tone, and any other style guides will only be able to research, and write, a single short page in a 4 hour sprint. Unless they are already an SME.

Probably also good to have a broad variety of topics to choose from as it's difficult to write documentation about something you're not already fairly well versed in.

Combined with templates for specific types of documentation. e.g.) tasks vs. concepts. To help with consistency and give people a solid foundation to start from.

> Beginner and intermediate experienced folks are the best for contributing to the docs because they would have the best understanding of its deficiencies.

Yes! Especially when it comes to doing things like figuring out what documentation is missing, or providing a review for documentation that someone else wrote. Kind of like user testing. But I think it's important to also make sure final content is either written or at least reviewed by an SME.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
